<template>
    <div class="Vue-content">
        
    <h2 id="Vue-인스턴스-만들기"><a href="#Vue-인스턴스-만들기" class="headerlink" title="Vue 인스턴스 만들기"></a>Vue 인스턴스 만들기</h2><p>모든 Vue 앱은 <code>Vue</code> 함수로 새 <strong>Vue 인스턴스</strong>를 만드는 것부터 시작합니다.</p>
    <figure class="highlight js"><table><tr><td class="code"><pre><span class="line"><span class="keyword">var</span> vm = <span class="keyword">new</span> Vue(&#123;</span><br><span class="line">  <span class="comment">// 옵션</span></span><br><span class="line">&#125;)</span><br></pre></td></tr></table></figure>
    <br><p>엄격히 <a href="https://en.wikipedia.org/wiki/Model_View_ViewModel" target="_blank" rel="noopener">MVVM 패턴</a>과 관련이 없지만 Vue의 디자인은 부분적으로 그것에 영감을 받았습니다. 컨벤션으로, Vue 인스턴스를 참조하기 위해 종종 변수 <code>vm</code>(ViewModel의 약자)을 사용합니다.</p>
<p>Vue 인스턴스를 인스턴스화 할 때는 데이터, 템플릿, 마운트할 엘리먼트, 메소드, 라이프사이클 콜백 등의 옵션을 포함 할 수있는 <strong>options 객체</strong>를 전달 해야합니다. 전체 옵션 목록은 <a href="../api">API reference</a>에서 찾을 수 있습니다.</p>
<br><p><code>Vue</code> 생성자는 미리 정의 된 옵션으로 재사용 가능한 <strong>컴포넌트 생성자</strong>를 생성하도록 확장 될 수 있습니다<br>Vue 앱은 <code>new Vue</code>를 통해 만들어진 <code>루트 Vue 인스턴스</code>로 구성되며 선택적으로 중첩이 가능하고 재사용 가능한 컴포넌트 트리로 구성됩니다. 예를 들어 Todo 앱의 컴포넌트 트리는 다음과 같습니다.</p>
<br><figure class="highlight plain"><table><tr><td class="code"><pre><span class="line">Root Instance</span><br><span class="line">└─ TodoList</span><br><span class="line">   ├─ TodoItem</span><br><span class="line">   │  ├─ DeleteTodoButton</span><br><span class="line">   │  └─ EditTodoButton</span><br><span class="line">   └─ TodoListFooter</span><br><span class="line">      ├─ ClearTodosButton</span><br><span class="line">      └─ TodoListStatistics</span><br></pre></td></tr></table></figure>
<p>확장된 인스턴스를 만들수는 있으나 대개 템플릿에서 사용자 지정 엘리먼트로 선언적으로 작성하는 것이 좋습니다. 나중에 <a href="components.html">컴포넌트 시스템</a>에 대해 자세히 설명합니다. 지금은 모든 Vue 컴포넌트가 본질적으로 확장된 Vue 인스턴스라는 것을 알아야 합니다.</p>
<br><br><h2 id="속성과-메소드"><a href="#속성과-메소드" class="headerlink" title="속성과 메소드"></a>속성과 메소드</h2><p>각 Vue 인스턴스는 <code>data</code> 객체에 있는 모든 속성을 <strong>프록시</strong> 처리 합니다.</p>
<figure class="highlight js"><table><tr><td class="code"><pre><span class="line"><span class="comment">// 데이터 객체</span></span><br><span class="line"><span class="keyword">var</span> data = &#123; <span class="attr">a</span>: <span class="number">1</span> &#125;</span><br><span class="line"></span><br><span class="line"><span class="comment">// Vue인스턴스에 데이터 객체를 추가합니다.</span></span><br><span class="line"><span class="keyword">var</span> vm = <span class="keyword">new</span> Vue(&#123;</span><br><span class="line">  data: data</span><br><span class="line">&#125;)</span><br><span class="line"></span><br><span class="line"><span class="comment">// 같은 객체를 참조합니다!</span></span><br><span class="line">vm.a === data.a <span class="comment">// =&gt; true</span></span><br><span class="line"></span><br><span class="line"><span class="comment">// 속성 설정은 원본 데이터에도 영향을 미칩니다.</span></span><br><span class="line">vm.a = <span class="number">2</span></span><br><span class="line">data.a <span class="comment">// =&gt; 2</span></span><br><span class="line"></span><br><span class="line"><span class="comment">// ... 당연하게도</span></span><br><span class="line">data.a = <span class="number">3</span></span><br><span class="line">vm.a <span class="comment">// =&gt; 3</span></span><br></pre></td></tr></table></figure>
<br><p>데이터가 변경되면 화면은 다시 렌더링됩니다. 유념할 점은, <code>data</code>에 있는 속성들은 인스턴스가 생성될 때 존재한 것들만 <strong>반응형</strong>이라는 것입니다. 즉, 다음과 같이 새 속성을 추가하면:</p>
<br><figure class="highlight js"><table><tr><td class="code"><pre><span class="line">vm.b = <span class="string">'hi'</span></span><br></pre></td></tr></table></figure>
<br><p><code>b</code>가 변경되어도 화면이 갱신되지 않습니다. 어떤 속성이 나중에 필요하다는 것을 알고 있으며, 빈 값이거나 존재하지 않은 상태로 시작한다면 아래와 같이 초기값을 지정할 필요가 있습니다.</p>
<br><figure class="highlight js"><table><tr><td class="code"><pre><span class="line">data: &#123;</span><br><span class="line">  newTodoText: <span class="string">''</span>,</span><br><span class="line">  visitCount: <span class="number">0</span>,</span><br><span class="line">  hideCompletedTodos: <span class="literal">false</span>,</span><br><span class="line">  todos: [],</span><br><span class="line">  error: <span class="literal">null</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<br><p>여기에서 유일한 예외는 <code>Object.freeze ()</code>를 사용하는 경우입니다. 이는 기존 속성이 변경되는 것을 막아 반응성 시스템이 추적할 수 없다는 것을 의미합니다.</p>
<br><figure class="highlight js"><table><tr><td class="code"><pre><span class="line"><span class="keyword">var</span> obj = &#123;</span><br><span class="line">  foo: <span class="string">'bar'</span></span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="built_in">Object</span>.freeze(obj)</span><br><span class="line"></span><br><span class="line"><span class="keyword">new</span> Vue(&#123;</span><br><span class="line">  el: <span class="string">'#app'</span>,</span><br><span class="line">  data: obj</span><br><span class="line">&#125;)</span><br></pre></td></tr></table></figure>
<br><figure class="highlight html"><table><tr><td class="code"><pre><span class="line"><span class="tag">&lt;<span class="name">div</span> <span class="attr">id</span>=<span class="string">"app"</span>&gt;</span></span><br><span class="line">  <span class="tag">&lt;<span class="name">p</span>&gt;</span>&#123;&#123; foo &#125;&#125;<span class="tag">&lt;/<span class="name">p</span>&gt;</span></span><br><span class="line">  <span class="comment">&lt;!-- obj.foo는 더이상 변하지 않습니다! --&gt;</span></span><br><span class="line">  <span class="tag">&lt;<span class="name">button</span> <span class="attr">v-on:click</span>=<span class="string">"foo = 'baz'"</span>&gt;</span>Change it<span class="tag">&lt;/<span class="name">button</span>&gt;</span></span><br><span class="line"><span class="tag">&lt;/<span class="name">div</span>&gt;</span></span><br></pre></td></tr></table></figure>
<br><br><p>Vue 인스턴스는 데이터 속성 이외에도 유용한 인스턴스 속성 및 메소드를 제공합니다. 다른 사용자 정의 속성과 구분하기 위해 <code>$</code> 접두어를 붙였습니다.</p>
    <br><br><p>예:</p>
    <figure class="highlight js"><table><tr><td class="code"><pre><span class="line"><span class="keyword">var</span> data = &#123; <span class="attr">a</span>: <span class="number">1</span> &#125;</span><br><span class="line"><span class="keyword">var</span> vm = <span class="keyword">new</span> Vue(&#123;</span><br><span class="line">  el: <span class="string">'#example'</span>,</span><br><span class="line">  data: data</span><br><span class="line">&#125;)</span><br><span class="line"></span><br><span class="line">vm.$data === data <span class="comment">// =&gt; true</span></span><br><span class="line">vm.$el === <span class="built_in">document</span>.getElementById(<span class="string">'example'</span>) <span class="comment">// =&gt; true</span></span><br><span class="line"></span><br><span class="line"><span class="comment">// $watch 는 인스턴스 메소드 입니다.</span></span><br><span class="line">vm.$watch(<span class="string">'a'</span>, <span class="function"><span class="keyword">function</span> (<span class="params">newVal, oldVal</span>) </span>&#123;</span><br><span class="line">  <span class="comment">// `vm.a`가 변경되면 호출 됩니다.</span></span><br><span class="line">&#125;)</span><br></pre></td></tr></table></figure>
    <p>나중에 <a href="../api/#Instance-Properties">API reference</a>에서 인스턴스 속성과 메소드 전체 목록을 살펴보세요.</p>
    <h2 id="인스턴스-라이프사이클-훅"><a href="#인스턴스-라이프사이클-훅" class="headerlink" title="인스턴스 라이프사이클 훅"></a>인스턴스 라이프사이클 훅</h2><p>각 Vue 인스턴스는 생성될 때 일련의 초기화 단계를 거칩니다. 예를 들어, 데이터 관찰 설정이 필요한 경우, 템플릿을 컴파일하는 경우, 인스턴스를 DOM에 마운트하는 경우, 그리고 데이터가 변경되어 DOM를 업데이트하는 경우가 있습니다. 그 과정에서 사용자 정의 로직을 실행할 수있는 <strong>라이프사이클 훅</strong> 도 호출됩니다. 예를 들어, <a href="../api/#created"><code>created</code></a> 훅은 인스턴스가 생성된 후에 호출됩니다. 예:</p>
    <figure class="highlight js"><table><tr><td class="code"><pre><span class="line"><span class="keyword">new</span> Vue(&#123;</span><br><span class="line">  data: &#123;</span><br><span class="line">    a: <span class="number">1</span></span><br><span class="line">  &#125;,</span><br><span class="line">  created: <span class="function"><span class="keyword">function</span> (<span class="params"></span>) </span>&#123;</span><br><span class="line">    <span class="comment">// `this` 는 vm 인스턴스를 가리킵니다.</span></span><br><span class="line">    <span class="built_in">console</span>.log(<span class="string">'a is: '</span> + <span class="keyword">this</span>.a)</span><br><span class="line">  &#125;</span><br><span class="line">&#125;)</span><br><span class="line"><span class="comment">// =&gt; "a is: 1"</span></span><br></pre></td></tr></table></figure>
    <p>인스턴스 라이프사이클의 여러 단계에서 호출될 다른 훅도 있습니다. 그 예로 <a href="../api/#mounted"><code>mounted</code></a>,<a href="../api/#updated"><code>updated</code></a> 및 <a href="../api/#destroyed"><code>destroyed</code></a>가 있습니다. 모든 라이프사이클 훅은 <code>this</code> 컨텍스트가 호출하는 Vue 인스턴스를 가리키며 호출됩니다. Vue 세계에서 “컨트롤러”의 컨셉이 어디에 있는지 궁금할 수 있습니다. 답은 컨트롤러가 없습니다. 컴포넌트의 사용자 지정 로직은 이러한 라이프사이클 훅으로 분할됩니다.</p>
    <p class="tip">options 속성이나 콜백에 <code>created: () =&gt; console.log(this.a)</code> 이나 <code>vm.$watch(&#39;a&#39;, newValue =&gt; this.myMethod())</code> 와 같은 <a href="https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Functions/%EC%95%A0%EB%A1%9C%EC%9A%B0_%ED%8E%91%EC%85%98" target="_blank" rel="noopener">화살표 함수</a> 사용을 지양하기 바랍니다.<br>화살표 함수들은 부모 컨텍스트에 바인딩되기 때문에, <code>this</code> 컨텍스트가 호출하는 Vue 인스턴스에서 사용할 경우 <code>Uncaught TypeError: Cannot read property of undefined</code> 또는 <code>Uncaught TypeError: this.myMethod is not a function</code>와 같은 오류가 발생하게 됩니다.</p>

        </div>
</template>
<script>
export default {
    
}
</script>
<style scoped>
    .Vue-content{
        padding:100px;
    }
</style>